# This was generated by ChatGPT

import requests
from bs4 import BeautifulSoup
import random
import re
import os

num_docs = 1000
min_words = 1000
max_words = 2000

def save_string_as_file(content, directory, file_name):
    file_path = os.path.join(directory, file_name + '.txt')
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

def download_random_document():
    url = "https://en.wikipedia.org/wiki/Special:Random"
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        document = soup.get_text(separator=' ')
        document = re.sub('\s+', ' ', document)
        word_count = len(document.split())
        if word_count >= min_words and word_count <= max_words:
            return document

for i in range(num_docs):
    document = download_random_document()
    if document == None:
        continue
    filename = "doc_" + str(i)
    save_string_as_file(document, "documents", filename)
